### ISSUE TITLE
Action Plan 1

### ISSUE THREAD

**Issue by tawfiknasser** [FACN4/week3_espionageProject#1]
#### Our project :  Live weekly total commit for the three cohorts (FACN4,FAC14,FACG5)

- [X] First Meeting & Discussion for the project idea 

![42283156-81f4-4a08-b7dc-7cdb1b9b6229](https://user-images.githubusercontent.com/36166288/42806936-3671685a-89b8-11e8-896c-fa2f1a001f16.jpeg)

- [x] Validate Concept  

- [x] Software Architecture

**Comment by tawfiknasser** [comment]
Validate Concept :

- [ ] GitHub API (private organizations)

- [ ] Graphs 

- [ ] googleMaps

**Comment by BenNewman90** [comment]
## Rate limiting
For API requests using Basic Authentication or OAuth, you can make up to 5000 requests per hour. Authenticated requests are associated with the authenticated user, regardless of whether Basic Authentication or an OAuth token was used. This means that all OAuth applications authorized by a user share the same quota of 5000 requests per hour when they authenticate with different tokens owned by the same user.

For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.

https://developer.github.com/v3/#rate-limiting

**Comment by DenisKent** [comment]
#2 
@Solk10 and I found google graphs and it works

**Comment by Solk10** [comment]
![week3plan1](https://user-images.githubusercontent.com/39616416/42814022-8e48832a-89cb-11e8-966b-99401f1607eb.jpg)

**Comment by DenisKent** [comment]
## Latest version of the Software Architecture:
![whatsapp image 2018-07-17 at 15 16 51](https://user-images.githubusercontent.com/28222381/42820397-bba908b8-89de-11e8-810b-17c9bb933902.jpeg)
