### ISSUE TITLE
rewrite the test script 

### ISSUE THREAD

**Issue by tawfiknasser** [FACN4/week3_espionageProject#16]
rewrite the test script 

https://github.com/FACN4/week3_espionageProject/blob/28e02a347b8bab66fe8d4dd9737a7351a297530d/package.json#L7

**Comment by tawfiknasser** [comment]
@Solk10

**Comment by Solk10** [comment]
Is that what you mean ? 
  
"test": "nyc tape test.js | tap-spec"

**Comment by tawfiknasser** [comment]
exactly :dancer: 
 make sure that  "test.js" is the right destination

**Comment by Solk10** [comment]
@tawfiknasser  yess it is

**Comment by DenisKent** [comment]
done :+1:
