### ISSUE TITLE
Text shadow

### ISSUE THREAD

**Issue by matthall8** [FACN4/week3_espionageProject#50]
I like the colour pallete overall but find the text-shadow on the headers as difficult to read. Perhaps you could remove it and bold them or make the text size larger to make them stand out more.

![image](https://user-images.githubusercontent.com/9437789/42928623-7ef12726-8b40-11e8-9d4c-29e4afb38013.png)

**Comment by Solk10** [comment]
We could change that ofcourse but i see it clear enough Matt 🤔
