### ISSUE TITLE
What is temporaryFile.js?

### ISSUE THREAD

**Issue by shiryz** [FACN4/week3_espionageProject#51]
Where is this file being used? 
Why is it called temporary?
Very mysterious... please delete if you're not using it

**Comment by DenisKent** [comment]
The file is used to generate objects for testing. I'll tack it on to the bottom of the test file

**Comment by shiryz** [comment]
A better name would be dummyData or testData

**Comment by shiryz** [comment]
Don't close your own issues please, tag me to do it :heart:
